### ISSUE TITLE
usage task fails

### ISSUE THREAD

**Issue by bitcoiners** [inertia186/drotto#14]
I am running latest git master
```
~/drotto# rake usage
rake aborted!
TinyTds::Error: Login failed for user 'steemit'. Reason: The account is disabled.
/usr/local/rvm/gems/ruby-2.4.1/gems/tiny_tds-1.3.0/lib/tiny_tds/client.rb:53:in `connect'
/usr/local/rvm/gems/ruby-2.4.1/gems/tiny_tds-1.3.0/lib/tiny_tds/client.rb:53:in `initialize'

```

**Comment by bulleric** [comment]
The dependancy steem_api requires access to the underlying service https://steemsql.com/
They changed recently their subscription model to a payed service.

As far as i see the cost for steemsql is now 10SBD per month 

> New subscription model
 SteemSQL has moved to a monthly subscription model. The default account/password “steemit/steemit” has been disabled.

Is steemdata an alternative?

**Comment by inertia186** [comment]
It is possible to use the pre-release version of steem_api, which supports subscription accounts.  But you might want to wait for the next release.

In the meantime, there is a report on Ganymede that is similar to `rake usage`:

https://steem-ganymede.herokuapp.com/charts/booster/net_transfers

Just change the url so it points to your bot.
