### ISSUE TITLE
rake aborted!

### ISSUE THREAD

**Issue by bendenn** [inertia186/drotto#18]
hey hello, i get this error:

rake aborted!
LoadError: cannot load such file -- yard
/home/bendenn/drotto/Rakefile:3:in `<top (required)>'
(See full trace by running task with --trace)

rake aborted!
LoadError: cannot load such file -- yard
/home/bendenn/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/home/bendenn/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/home/bendenn/drotto/Rakefile:3:in `<top (required)>'
/home/bendenn/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load'
/home/bendenn/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load_rakefile'
/home/bendenn/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:703:in `raw_load_rakefile'
/home/bendenn/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:104:in `block in load_rakefile'
/home/bendenn/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/home/bendenn/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:103:in `load_rakefile'
/home/bendenn/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:82:in `block in run'
/home/bendenn/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/home/bendenn/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/home/bendenn/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/home/bendenn/.rbenv/versions/2.5.1/bin/rake:23:in `load'
/home/bendenn/.rbenv/versions/2.5.1/bin/rake:23:in `<main>'

Can you give me a hint?

By the way, very nice work! 
Just hope that I get it to run;)

**Comment by inertia186** [comment]
Did you do `bundle install`?
