### ISSUE TITLE
drotto on golos

### ISSUE THREAD

**Issue by bitcoiners** [inertia186/drotto#4]
Hello.
I am trying to launch drotto on golos, but getting an error:
```
rake run
{ :DBG => "Remaining voting power: 100.00 % (recharged 0.00 % since last vote)" }
{ :DBG => "Last vote: 628 minutes ago; 0.0 minutes of recharge power unused in 100.00 %" }
rake aborted!
NoMethodError: undefined method `map' for nil:NilClass
Did you mean?  tap
/root/drotto/lib/drotto/bounce_job.rb:402:in `transfer_ids'
/root/drotto/lib/drotto.rb:34:in `find_bids'
/root/drotto/lib/drotto.rb:185:in `block in run'
/root/drotto/lib/drotto.rb:178:in `loop'
/root/drotto/lib/drotto.rb:178:in `run'
/root/drotto/Rakefile:54:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => run

```

**Comment by inertia186** [comment]
You should switch to the `develop` branch:

```bash
git checkout develop
```

**Comment by inertia186** [comment]
Also, please note that `rake bounce_stream` will not work right now due to missing information in the golos `get_block` response.

https://github.com/GolosChain/golos/issues/281

**Comment by inertia186** [comment]
`rake bounce_stream` is now working, as of 81b15e7bdddded996decc0daedb3218c8fdfd677.
